apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: pcxnyihys-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/pcxnyihys-java-quarkus-gitops